# Generated by Django 5.2.4 on 2025-07-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL логотипа')),
                ('link', models.URLField(verbose_name='Ссылка на оффер')),
                ('sum_min', models.IntegerField(verbose_name='Мин. сумма')),
                ('sum_max', models.IntegerField(verbose_name='Макс. сумма')),
                ('term_min', models.IntegerField(verbose_name='Мин. срок (дни)')),
                ('term_max', models.IntegerField(verbose_name='Макс. срок (дни)')),
                ('rate', models.FloatField(verbose_name='Ставка в день (%)')),
                ('approval_chance', models.IntegerField(verbose_name='Шанс одобрения (%)')),
                ('payout_speed_hours', models.FloatField(verbose_name='Скорость выплаты (часы)')),
                ('requirements', models.TextField(blank=True, help_text='Перечислите через точку с запятой', verbose_name='Требования')),
                ('get_methods', models.TextField(blank=True, help_text='Перечислите через точку с запятой', verbose_name='Способы получения')),
                ('repay_methods', models.TextField(blank=True, help_text='Перечислите через точку с запятой', verbose_name='Способы погашения')),
            ],
            options={
                'verbose_name': 'МФО',
                'verbose_name_plural': 'МФО',
            },
        ),
    ]
