# Generated by Django 5.2.4 on 2025-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfo',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ставка в день (%)'),
        ),
    ]
