# Generated by Django 5.2.4 on 2025-09-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mfo_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название оффера')),
                ('base_url', models.URLField(max_length=500, verbose_name='Базовая ссылка')),
                ('ref_source', models.CharField(max_length=100, verbose_name='Источник реферала (utm_content)')),
                ('ref', models.CharField(max_length=100, verbose_name='Реферальный код (utm_campaign)')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
    ]
