# Generated by Django 5.2.4 on 2025-09-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTMTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID пользователя')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=200, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='UTM Content')),
                ('utm_term', models.CharField(blank=True, max_length=200, verbose_name='UTM Term')),
                ('vk_ad_id', models.CharField(blank=True, max_length=100, verbose_name='VK Ad ID')),
                ('vk_ref', models.CharField(blank=True, max_length=200, verbose_name='VK Ref')),
                ('vk_ref_source', models.CharField(blank=True, max_length=200, verbose_name='VK Ref Source')),
                ('vk_platform', models.CharField(blank=True, max_length=100, verbose_name='VK Platform')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='URL страницы')),
                ('referrer', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('full_utm_data', models.JSONField(default=dict, verbose_name='Полные UTM данные')),
                ('full_user_data', models.JSONField(default=dict, verbose_name='Полные данные пользователя')),
                ('event_type', models.CharField(default='page_view', max_length=50, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'UTM Отслеживание',
                'verbose_name_plural': 'UTM Отслеживание',
                'ordering': ['-timestamp'],
            },
        ),
    ]
