# Generated by Django 5.2.4 on 2025-10-03 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_utmtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='VKUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_user_id', models.BigIntegerField(unique=True, verbose_name='VK ID пользователя')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('sex', models.IntegerField(blank=True, null=True, verbose_name='Пол (1-женский, 2-мужской)')),
                ('bdate', models.CharField(blank=True, max_length=20, verbose_name='Дата рождения')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления разрешены')),
                ('notifications_allowed', models.BooleanField(default=False, verbose_name='Пользователь разрешил уведомления в VK')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('total_visits', models.IntegerField(default=1, verbose_name='Всего визитов')),
                ('utm_source', models.CharField(blank=True, max_length=200, verbose_name='UTM Source')),
                ('utm_campaign', models.CharField(blank=True, max_length=200, verbose_name='UTM Campaign')),
                ('utm_content', models.CharField(blank=True, max_length=200, verbose_name='UTM Content')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Пользователь VK',
                'verbose_name_plural': 'Пользователи VK',
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок уведомления')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('segment', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Активные (были за последние 7 дней)'), ('inactive', 'Неактивные (не были более 7 дней)'), ('new', 'Новые (зарегистрированы за последние 3 дня)'), ('custom', 'Выборочная сегментация')], default='all', max_length=20, verbose_name='Сегмент')),
                ('filter_city', models.CharField(blank=True, max_length=100, verbose_name='Фильтр по городу')),
                ('filter_sex', models.IntegerField(blank=True, null=True, verbose_name='Фильтр по полу')),
                ('filter_utm_source', models.CharField(blank=True, max_length=200, verbose_name='Фильтр по UTM Source')),
                ('action_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка при клике')),
                ('action_type', models.CharField(blank=True, max_length=50, verbose_name='Тип действия (open_app, open_url)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланировано'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Отправлено')),
                ('total_delivered', models.IntegerField(default=0, verbose_name='Доставлено')),
                ('total_failed', models.IntegerField(default=0, verbose_name='Не доставлено')),
                ('total_clicked', models.IntegerField(default=0, verbose_name='Переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('target_users', models.ManyToManyField(blank=True, to='api.vkuser', verbose_name='Конкретные пользователи')),
            ],
            options={
                'verbose_name': 'Пуш-уведомление',
                'verbose_name_plural': 'Пуш-уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка'), ('clicked', 'Клик')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата клика')),
                ('vk_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ VK API')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.pushnotification', verbose_name='Уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_logs', to='api.vkuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-sent_at'],
            },
        ),
    ]
