# Generated by Django 5.0.3 on 2025-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vkuser_pushnotification_pushlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfo',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='mfo',
            name='link',
            field=models.URLField(max_length=500, verbose_name='Ссылка на оффер'),
        ),
    ]
