# Generated by Django 5.0.3 on 2025-11-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vkuser_messages_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рассылки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('schedule_type', models.CharField(choices=[('once', 'Разовая отправка'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Произвольное расписание')], default='once', max_length=20, verbose_name='Тип расписания')),
                ('schedule_time', models.TimeField(blank=True, null=True, verbose_name='Время отправки (для ежедневных)')),
                ('schedule_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время (для разовых)')),
                ('schedule_days', models.JSONField(blank=True, default=list, help_text='Дни недели для еженедельных (0=Понедельник, 6=Воскресенье)', verbose_name='Дни недели')),
                ('schedule_day_of_month', models.IntegerField(blank=True, help_text='День месяца для ежемесячных (1-31)', null=True, verbose_name='День месяца')),
                ('segment', models.CharField(choices=[('all', 'Все пользователи'), ('active', 'Активные (были за последние 7 дней)'), ('inactive', 'Неактивные (не были более 7 дней)'), ('new', 'Новые (зарегистрированы за последние 3 дня)'), ('custom', 'Выборочная сегментация')], default='all', max_length=20, verbose_name='Сегмент')),
                ('filter_city', models.CharField(blank=True, max_length=100, verbose_name='Фильтр по городу')),
                ('filter_sex', models.IntegerField(blank=True, null=True, verbose_name='Фильтр по полу')),
                ('filter_utm_source', models.CharField(blank=True, max_length=200, verbose_name='Фильтр по UTM Source')),
                ('max_sends_per_day', models.IntegerField(blank=True, help_text='Максимум отправок в день (null = без ограничений)', null=True, verbose_name='Лимит отправок в день')),
                ('total_sends_limit', models.IntegerField(blank=True, help_text='Общий лимит отправок (null = без ограничений)', null=True, verbose_name='Общий лимит')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата запуска')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Всего отправлено')),
                ('total_delivered', models.IntegerField(default=0, verbose_name='Всего доставлено')),
                ('total_failed', models.IntegerField(default=0, verbose_name='Всего ошибок')),
                ('target_users', models.ManyToManyField(blank=True, to='api.vkuser', verbose_name='Конкретные пользователи')),
            ],
            options={
                'verbose_name': 'Рассылка пуш-уведомлений',
                'verbose_name_plural': 'Рассылки пуш-уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок уведомления')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('action_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка при клике')),
                ('action_type', models.CharField(blank=True, max_length=50, verbose_name='Тип действия')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('times_used', models.IntegerField(default=0, verbose_name='Использовано раз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.pushcampaign', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Шаблон пуша',
                'verbose_name_plural': 'Шаблоны пушей',
                'ordering': ['campaign', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SentPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('failed', 'Ошибка'), ('clicked', 'Клик')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата клика')),
                ('vk_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ VK API')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_pushes', to='api.pushcampaign', verbose_name='Рассылка')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_pushes', to='api.pushtemplate', verbose_name='Шаблон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pushes', to='api.vkuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправленный пуш',
                'verbose_name_plural': 'Отправленные пуши',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='api_sentpus_sent_at_54f73f_idx'), models.Index(fields=['campaign', '-sent_at'], name='api_sentpus_campaig_901f0c_idx'), models.Index(fields=['user', '-sent_at'], name='api_sentpus_user_id_4a0ac2_idx')],
            },
        ),
    ]
