"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Убедимся, что os импортирован

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = ['*'] # Для Docker разрешаем все хосты


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Наши новые приложения
    'api',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Добавляем middleware для CORS
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # XFrameOptionsMiddleware отключен, так как настройка выполняется в nginx
    # для поддержки VK доменов (vk.com, vk.ru) согласно документации
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Для работы за Nginx (чтобы Django понимал, что запрос идет по HTTPS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Настройка X-Frame-Options для поддержки VK доменов
# Заголовок управляется через nginx для большей гибкости
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'babkimanki_db'),
        'USER': os.environ.get('DB_USER', 'babkimanki_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'change_this_password'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Настройки для статических файлов (для админки Django)
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для CORS: разрешаем доступ с адреса нашего фронтенда и VK доменов
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",  # ИСПРАВЛЕНИЕ: Vite dev server на порту 5174
    "http://127.0.0.1:5174",
    "https://utkaminiapp.ru",  # Продакшен
    "https://www.utkaminiapp.ru",
    # VK домены для поддержки мини-приложений
    "https://vk.com",
    "https://www.vk.com",
    "https://vk.ru",
    "https://www.vk.ru",
    "https://m.vk.com",
    "https://m.vk.ru",
]

# Разрешаем CORS для поддоменов serveo.net (для VK Tunnel)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.serveo\.net$",
]

CSRF_TRUSTED_ORIGINS = [
    'https://utkaminiapp.ru',
    'https://www.utkaminiapp.ru',
    # VK домены для поддержки мини-приложений
    'https://vk.com',
    'https://www.vk.com',
    'https://vk.ru',
    'https://www.vk.ru',
    'https://m.vk.com',
    'https://m.vk.ru',
]

# VK Mini App Settings
VK_APP_ACCESS_TOKEN = os.environ.get('VK_APP_ACCESS_TOKEN', '')
VK_APP_ID = os.environ.get('VK_APP_ID', '')
VK_GROUP_ID = os.environ.get('VK_GROUP_ID', '230927358')  # ID сообщества для отправки сообщений

# Sentry Configuration for Error Monitoring
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN and not DEBUG:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Set traces_sample_rate to 1.0 to capture 100% of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        traces_sample_rate=0.1,  # 10% в продакшене для экономии
        # If you wish to associate users to errors (assuming you are using
        # django.contrib.auth) you may enable sending PII data.
        send_default_pii=True,
        environment='production' if not DEBUG else 'development',
    )
